<?php

/**
 * Actency custom module to take nodes from a source and deploy them into a destination
 *
 * @author Manuel Grosrenaud
 * @author Pierre Lesbazeilles
 *
 * @todo
 * - vbo implementation    (enrich node selection mechanism befor export)
 * - manage taxonomy voc
 * - extend uuid to others entities than only nodes
 * - implement some logs
 */

/**
 * Implements hook_help().
 *
 * Show some help on each form provided by this module.
 */
function deploy_d2d_help($path) {
  $output = '';
  switch ($path) {
    case 'deploy_d2d/import-export/import':
      $output = t('Generate files in public://import');
      break;

    case 'deploy_d2d/import-export/export':
      $output = t('Load file in public://export and saves nodes ');
      break;
  }
  return $output;
}

/**
 * Implements hook_menu()
 */
function deploy_d2d_menu() {
  $items['admin/deploy_d2d/import-export'] = array(
    'title' => 'deploy_d2d',
    'description' => 'deploy_d2d.',
    'page callback' => 'deploy_d2d_deploy_page',
    'access arguments' => array('access administration pages'),

  );
  $items['admin/deploy_d2d/import-export/import'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deploy_d2d_import_form'),
    'access arguments' => array('access content'),
    'title' => 'import',
  );
  $items['admin/deploy_d2d/import-export/export'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deploy_d2d_export_form'),
    'access arguments' => array('access content'),
    'title' => 'export',
  );
  return $items;
}

/**
 * Menu callbacks
 */
function deploy_d2d_deploy_page() {
  $output = l('import', 'admin/deploy_d2d/import-export/import');
  $output .= '<br/>' . l('export', 'admin/deploy_d2d/import-export/export');
  return $output;
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function deploy_d2d_export_form($form, &$form_state) {


  $form['submit'] = array('#type' => 'submit', '#value' => t('Export'));
  return $form;
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function deploy_d2d_import_form($form, &$form_state) {
  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Options'),
    '#weight' => -5,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['options']['delete_atom'] = array(
    '#type' => 'checkbox',
    '#title' => t('Delete all Sclad Atom before import.'),
    '#return_value' => 1,
    '#default_value' => 0,
  );
  $form['options']['preserve_atom'] = array(
    '#type' => 'checkbox',
    '#title' => t('Preserve SIDs before import.'),
    '#return_value' => 1,
    '#default_value' => 1,
  );
  $form['submit'] = array('#type' => 'submit', '#value' => t('Import'));
  return $form;
}

/**
 * @param $form
 * @param $form_state
 */
function deploy_d2d_export_form_submit($form, &$form_state) {
$taxos = $taxo_order = $vocabs = $users = $menu_links = array();
  $file = DRUPAL_ROOT . '/includes/utility.inc';
  if (is_file($file)) {
    require_once $file;
  }

  //export entities
  $entities_export=array('taxonomy_term', 'user', 'scald_atom' );
  foreach($entities_export as $entitie_export){
    $entities = entity_load($entitie_export);
    file_put_contents('public://export/'.$entitie_export.'.export', drupal_var_export($entities));
  }
  //files need absolute url
  $files = deploy_d2d_get_files();
  file_put_contents('public://export/file.export', drupal_var_export($files));

  drupal_set_message(t('Export: succeeded (files are in public://export/)'));
}

/**
 * @param $form
 * @param $form_state
 */
function deploy_d2d_import_form_submit($form, &$form_state) {
  if ($form_state['values']['delete_atom'] == 1) {
    drupal_set_message(t('Begin Delete Atoms'));
    $sids = deploy_d2d_get_atoms();
    scald_atom_delete_multiple($sids);
    drupal_set_message(t('Delete @countnode Scald atoms', array('@countnode' => count($sids))));
    //Truncate table automatically reset the Autoincrement values to 0.
    db_truncate('scald_atoms')->execute();
    drupal_set_message(t('truncate table scald_atoms'));
  }


  $preserve_sid = ($form_state['values']['preserve_atom'] == 1) ? TRUE : FALSE;

  $taxos = array();
  $users = array();
  $scalds = array();

  // Get data
  $files_file_import = file_get_contents('public://import/file.export');
  $files_file = deploy_d2d_drupal_import($files_file_import);

  $taxo_file_import = file_get_contents('public://import/taxonomy_term.export');
  $taxo_import = deploy_d2d_drupal_import($taxo_file_import);

  $users_file_import = file_get_contents('public://import/user.export');
  $users_import = deploy_d2d_drupal_import($users_file_import);

  $scald_file_import = file_get_contents('public://import/scald_atom.export');
  $scalds_import = deploy_d2d_drupal_import($scald_file_import);

  $i = 0;

  // Import scald
  foreach ($scalds_import as $current_scald) {
    if (!array_key_exists($current_scald->sid, $scalds)) {
      $scalds[$current_scald->sid] = deploy_d2d_process_scald_import($current_scald, $scalds_import, $taxo_import, $users_import, $scalds, $taxos, $users, $files_file, $i, $preserve_sid,$url_to_download);
    }
  }
  drupal_set_message(t('Import @countnode  scalds t', array('@countnode' => count($scalds))));


  $file = DRUPAL_ROOT . '/includes/utility.inc';
  if (is_file($file)) {
    require_once $file;
  }
  file_put_contents('public://import/taxonomy_term-report.import', drupal_var_export($taxos));
  file_put_contents('public://import/user-report.import', drupal_var_export($users));
  file_put_contents('public://import/scald_atom-report.import', drupal_var_export($scalds));
  file_put_contents('public://import/file-report.import', drupal_var_export($files_file));
  drupal_set_message(t('Import: finished'));
}

/**
 * Import callback.
 */
function deploy_d2d_drupal_import($code_string) {
  if (substr(ltrim($code_string), 0, 6) == "array(") {
    $nodes = eval('return ' . $code_string . ';');
    if (is_array($nodes)) {
      return deploy_d2d_drupal_decode_objects($nodes);
    }
  }
}

/**
 * Recursively convert arrays back to objects.
 *
 * This is only for backwards compatibility with the deprecated node_code format.
 */
function deploy_d2d_drupal_decode_objects($array) {
  foreach ($array as $k => $v) {
    if (is_array($v)) {
      $array[$k] = deploy_d2d_drupal_decode_objects($v);
    }
  }
  if (isset($array['#_export_node_encode_object'])) {
    unset($array['#_export_node_encode_object']);
    $array = (object) $array;
  }
  return $array;
}


/**
 * @param null $nids
 * @return array
 */
function deploy_d2d_get_files(){
  $files = array();
  $result = db_query('SELECT m.fid FROM {file_managed} m');
  foreach ($result as $row) {
    if ($file = file_load($row->fid)) {
      $files[$file->fid] = (array) $file;
      $files[$file->fid]['url'] = file_create_url($file->uri);
    }
  }
  return $files;
}

/**
 * @return mixed
 */
function deploy_d2d_get_atoms() {
  return db_select('scald_atoms', 'atoms')
    ->fields('atoms', array('sid'))
    ->execute()
    ->fetchCol();
}

/**
 * @param $scald
 * @param $scalds_import
 * @param $taxo_import
 * @param $users_import
 * @param $scalds
 * @param $taxos
 * @param $users
 * @param $files
 * @param $i
 * @param bool $preserve_sid
 * @return bool
 */
function deploy_d2d_process_scald_import($scald, $scalds_import, $taxo_import, $users_import, &$scalds, &$taxos, &$users, &$files, &$i, $preserve_sid = FALSE) {
  $sid = $scald->sid;
  if (!array_key_exists($sid, $scalds)) {
    $scald_destination = clone $scald;
    if (!$preserve_sid) {
      unset($scald_destination->sid);
    }
    else {
      scald_atom_delete($scald_destination->sid);
      //insert values with protect sid
      db_insert('scald_atoms')// Table name no longer needs {}
      ->fields(array(
        'sid' => $scald_destination->sid,
        'provider' => $scald_destination->provider,
        'type' => $scald_destination->type,
        'base_id' => $scald_destination->base_id,
        'language' => $scald_destination->language,
        'publisher' => $scald_destination->publisher,
        'actions' => $scald_destination->actions,
        'title' => $scald_destination->title,
        'data' => serialize($scald_destination->data),
        'created' => REQUEST_TIME,
        'changed' => REQUEST_TIME,
      ))
        ->execute();


    }
    $user = $users[$scald->publisher];
    if ($user->uid) {
      $scald_destination->publisher = $user->uid;
    }

    $scalds[$sid] = $scald_destination;
    //watchdog("scald_destination",print_r($scald_destination,true));
    foreach ($scald_destination as $field_name => $field) {
      if (substr($field_name, 0, 5) == 'field' ||
        $field_name == 'base_entity' ||
        substr($field_name, 0, 5) == 'scald'
      ) {
        $field_info = field_info_field($field_name);
        switch ($field_info['type']) {
          case 'image':
            if (isset($scald_destination->{$field_name}[LANGUAGE_NONE][0])) {
              foreach ($scald_destination->{$field_name}[LANGUAGE_NONE] as $k => $image) {
                $fid = $scald_destination->{$field_name}[LANGUAGE_NONE][$k]['fid'];
                $newfile = deploy_d2d_check_file($fid, $files);
                $scald_destination->{$field_name}[LANGUAGE_NONE][$k] = (array)$newfile;
              }
            }
            break;
          case 'taxonomy_term_reference':
            if (isset($scald_destination->{$field_name}[LANGUAGE_NONE][0])) {
              foreach ($scald_destination->{$field_name}[LANGUAGE_NONE] as $k => $tid) {
                if (isset($tid['tid'])) {
                  $ref_tid = (int) $tid['tid'];
                  if (!array_key_exists($ref_tid, $taxos)) {
                    if (array_key_exists($ref_tid, $taxo_import)) {
                      $taxos[$ref_tid] = deploy_d2d_check_taxo($ref_tid, 1, $taxo_import);
                      $scald_destination->{$field_name}[LANGUAGE_NONE][$k]['tid'] = $taxos[$ref_tid]->tid;
                    }
                    else {
                      unset($scald_destination->{$field_name}[LANGUAGE_NONE][$k]);
                    }
                  }
                  else {
                    $scald_destination->{$field_name}[LANGUAGE_NONE][$k]['tid'] = $taxos[$ref_tid]->tid;
                  }
                }
              }
            }
            break;
          default:
            break;
        }
      }
    }

    // node_object_prepare($node_destination);
    // $node_destination = node_submit($node_destination); // Prepare node for saving
    try {
      $i++;
      scald_atom_save($scald_destination);
      $success = TRUE;
      //    $nodes[$nid] = $node_destination;
      return $scald_destination;
    } catch (Exception $e) {
      // Do your error handling here.
      drupal_set_message(t('Atoms id  @sid not saved  due to an unexpected error', array('@sid' => $scald_destination->sid)));
      return FALSE;
    }
  }
  return FALSE;
}

/**
 * @param $users_import
 * @return mixed
 */
function deploy_d2d_process_users_import($users_import) {
  $users_destination = array();
  foreach ($users_import as $user) {
    $uid = $user->uid;
    if ($uid > 1) {
      $user_destination = ($user->mail) ? user_load_by_mail(array('mail' => $user->mail)) : FALSE;
      if (!$user_destination || $user_destination->uid == 0) { //pas de user existant je verifie dans les uuid
        if (module_exists('uuid') && function_exists('entity_uuid_load') &&
          $user->uuid && $user_destinationuuuid = entity_uuid_load('user', array($user->uuid))
        ) {
          unset($user->uid);
          $user->uid = $user_destinationuuuid->uid;
          $user->uuid = $user_destinationuuuid->uuid;
          $user_destination = user_save($user);
        }
        else {
          unset($user->uid);
          $user_destination = user_save($user);
        }
      }
      else {
        $user->uid = $user_destination->uid;
        $user_destination = user_save($user);
      }
    }
    else {
      $user_destination = $user;
    }
    $users[$uid] = $user_destination;
  }

  return $users;
}


/**
 * Check if taxo aready exists
  * @param $tid
 * @param $vid
 * @param $taxo_import_order
 * @return stdClass|term
 */
function deploy_d2d_check_taxo($tid, $vid, $taxo_import_order) {
  $term = $taxo_import_order[$tid];
  if (taxonomy_get_term_by_name($term->name, $vid)) {
    $taxo = taxonomy_get_term_by_name($term->name, $vid);
  }
  else {
    $taxo = deploy_d2d_create_taxonomy_term($term->name, $vid, $ptid = 0);
  }
  return $taxo;
}


/**
* Create a taxonomy term  .
 *
 * @param $name
 * @param $vid
 * @param int $ptid
 * @return stdClass|term
 */
function deploy_d2d_create_taxonomy_term($name, $vid, $ptid = 0) {
  $term = new stdClass();
  $term->name = $name;
  $term->vid = $vid;
  if ($ptid != 0) {
    $term->parent = $ptid;
  }
  else {
    $term->parent = NULL;
  }
  taxonomy_term_save($term);
  return $term;
}

/**
 * Check if user aready exists
 * @return stdClass|user
 */
function deploy_d2d_check_user($uid, $users_import_order) {
  $user = clone $users_import_order[$uid];
  if (user_load($user->uid) !== FALSE) {
    $user_local = user_load($user->uid);
    if ($user_local->name == $user->name) {
      return $user;
    }
  }
  return deploy_d2d_create_user($user);
}

/**
 * Create a user and return the uid.
 *  * @return array|user
 */
function deploy_d2d_create_user($user) {
 if ($user->uid>1){
  unset($user->uid);
  user_save($user);
 }
  return $user;
}


/**Check if files exists
 * @param null $fid
 * @param array $fids
 * @return array|bool
 */
function deploy_d2d_check_file($fid = NULL, $fids = array()) {

  $file = $fids[$fid];

  if ($file) {
    $uuid = "";
    if (isset($file->uuid)) {
      $uuid = $file->uuid;
    }
    elseif ($file['uuid']) {
      $uuid = $file['uuid'];
    }

    //check if file exist have universal id (uuid)
    if (module_exists('uuid') && function_exists('entity_uuid_load') && !empty($uuid) && ($file_destination = entity_uuid_load('file', array($uuid)))) {
      return $file_destination;
    }
    //download file
    return download_external_file($file['url'], $file['uri'], FILE_EXISTS_RENAME, TRUE, $uuid);
  }
  return $file;
}

/**
 *
 * param string $url
 *    Full url to file to download
 * param string $uri
 *    Drupal uri of where to save file public://archive/test.pdf
 * param int $save_mode
 *    File save mode from drupal core, ex FILE_EXISTS_REPLACE
 * http://www.patrickjwaters.com/blog/2013-08-22/drupal-7-how-programmatically-download-files-optionally-save-them-managed-files-save
 */
function download_external_file($url, $uri, $save_mode = FILE_EXISTS_RENAME, $manage_file = TRUE, $uuid = "") {
  $url_info = parse_url($url);
  $url_path_info = pathinfo($url_info['path']);

  //This helps with filenames with spaces
  $url = $url_info['scheme'] . '://' . $url_info['host'] . $url_path_info['dirname'] . '/' . rawurlencode($url_path_info['basename']);

  //Need to remove the filename from the uri
  $uri_target = file_uri_target($uri);
  $uri_scheme = file_uri_scheme($uri);
  $uri_path_info = pathinfo($uri_target);
  $directory = file_stream_wrapper_uri_normalize($uri_scheme . "://" . $uri_path_info['dirname']);
  if (file_prepare_directory($directory, FILE_CREATE_DIRECTORY)) {
    $drupal_result = drupal_http_request($url);

    print_r($uuid);
    if (!empty($drupal_result->data) && !isset($drupal_result->error)) {
      $path = file_stream_wrapper_uri_normalize($uri);
      if ($manage_file) {

        $new_file = file_save_data($drupal_result->data, $path, $save_mode);
        if (!empty($uuid) && is_object($new_file) && module_exists('uuid') && function_exists('entity_uuid_load')){
          $new_file->uuid=$uuid;
          $new_file = file_save($new_file);
        }
      }
      else {
        return file_unmanaged_save_data($drupal_result->data, $path, $save_mode);
      }
    }
    else {
      drupal_set_message(t('Error downloading file, no data recieved for @url', array('@url' => $url)));

      return FALSE;
    }

    $new_file->display = 1;
    return $new_file;
  }
  else {
    drupal_set_message(t('Could not create directory @directory', array('@$directory' => $directory)));
  }
}

